# 이름/학번

이름:20171722

학번:이장범

In [ ]:
import numpy as np
import torch

# Example dataset

강의를 위해서 임의의 dataset을 준비하겠습니다.
예제로 봐주시고, 큰 물리적 의미는 부여하지 않겠습니다.

- Data는 장미과와 국화과의 A 효소, B 효소, C 효소, D 효소를 측정한 값이라고 가정합니다.
- Label은 각 sample이 장미인지 (0) 국화인지 (1)에 대한 정보라고 가정합니다.

In [ ]:
batch_size = 10
num_feature = 4
torch.manual_seed(0)

X_batch = torch.randn(batch_size, num_feature)
Y_batch = (torch.sum(X_batch, dim=1)>0).type(torch.float).reshape(-1,1)

In [ ]:
X_batch

tensor([[-1.1258, -1.1524, -0.2506, -0.4339],
        [ 0.8487,  0.6920, -0.3160, -2.1152],
        [ 0.3223, -1.2633,  0.3500,  0.3081],
        [ 0.1198,  1.2377,  1.1168, -0.2473],
        [-1.3527, -1.6959,  0.5667,  0.7935],
        [ 0.5988, -1.5551, -0.3414,  1.8530],
        [-0.2159, -0.7425,  0.5627,  0.2596],
        [-0.1740, -0.6787,  0.9383,  0.4889],
        [ 1.2032,  0.0845, -1.2001, -0.0048],
        [-0.5181, -0.3067, -1.5810,  1.7066]])

In [ ]:
Y_batch

tensor([[0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.]])

# Notation 정리

강의자료와 비교하면 

\begin{align*}
\text{X_batch} = 
\begin{bmatrix}
(x^{(1)})^\top\\
(x^{(2)})^\top\\
\vdots \\
(x^{(m)})^\top
\end{bmatrix}, \quad
\text{Y_batch} = 
\begin{bmatrix}
y^{(1)}\\
y^{(2)}\\
\vdots \\
y^{(m)}
\end{bmatrix}
\end{align*}

# Example Problem: Single Neuron

- 한개의 neuron이 있다고 가정하고 $\mathbb{R}^4$ 를 입력받아서 $\mathbb{R}$로 출력한다고 가정합니다.
- Activation 함수는 ReLU 함수, 즉, 
\begin{align*}
\text{ReLU}(x) = \max(0, x)
\end{align*}
를 사용한다고 가정합니다.

Neuron을 통해서 batch sample 전체를
\begin{align*}
Z = \begin{bmatrix}
(w^T x^{(1)} + b)^T \\
(w^T x^{(2)} + b)^T \\
\vdots \\
(w^T x^{(m)} + b)^T
\end{bmatrix} 
\end{align*}
연산을 수행해서 $Z$를 구하세요.

- $w$는 random Gaussian으로 생성하세요. 위에서 예기한 입력과 출력이 맞도록 weight를 생성하세요.
- Bias $b$는 1로 설정




In [ ]:
# 답 작성

W = torch.randn(num_feature, 1)
b = 1
Z = torch.matmul(X_batch, W)+b
print(Z)

tensor([[ 0.6020],
        [ 1.6919],
        [-0.3206],
        [-0.8471],
        [-1.2320],
        [ 1.5082],
        [-0.6258],
        [-1.3570],
        [ 3.9385],
        [ 4.6839]])


원하는 연산을 하는지 확인하도록 합니다

In [ ]:
z_loop = torch.empty(batch_size, 1)
for i in torch.arange(batch_size):
    z_loop[i,:] = torch.matmul(W.T, X_batch[i,:].T)+b
print(z_loop)

tensor([[ 0.6020],
        [ 1.6919],
        [-0.3206],
        [-0.8471],
        [-1.2320],
        [ 1.5082],
        [-0.6258],
        [-1.3570],
        [ 3.9385],
        [ 4.6839]])


## Problem 1
ReLU 함수를 작성하고 위에서 찾은 $Z$의 각 원소에 ReLU 함수를 적용하여 `a`라는 변수에 저장하세요.

- torch.clamp() 함수를 공부하고 적용하세요




In [ ]:
# 답 작성:

def ReLU(x):
    a=torch.clamp(x,min=0)
    return a

A = ReLU(Z)

print(A)

tensor([[0.6020],
        [1.6919],
        [0.0000],
        [0.0000],
        [0.0000],
        [1.5082],
        [0.0000],
        [0.0000],
        [3.9385],
        [4.6839]])


# Single Layer Network

- 한개의 Layer에 $k=5$개의 Neuron 이 있는 network를 구성하고 출력을 구하세요
- Activation function은 모든 neuron에 ReLU를 적용합니다
- 모든 weight는 Gaussian 분포로 랜덤 생성하세요 `torch.randn()`
- $i$ 번째 neuron의 weight들을 $w_i$라고 할때,
\begin{align*}
\text{W} = \begin{bmatrix}
w_1, w_2, w_3, w_4, w_5
\end{bmatrix}
\end{align*}
라고 하고, weight matrix `W`를 만드세요.
  - `W = torch.randn(???, ???)` 으로 생성
- Bias 역시 `b`라는 `tensor`에 저장하고, 각 neuron 별로 `1`로 설정합니다
  - `b = torch.ones(???,???)`
- 아래 problem 2-2에서 수업에서 배운 $Z$ 행렬과 $A$ 행렬을 구하세요

# Problem 2-1
`Z` 행렬과 `A` 행렬의 차원은 어떻게 나와야하나요?

답 작성)

Z 는 (10,1), 
A 는 (10,5)

# Problem 2-2 
위에서 요구한 코딩을 완성하세요

In [ ]:
# 답 작성

W = torch.randn(4,5)
b = torch.ones(10,5) 

Z = torch.add(torch.matmul(X_batch,W),b)
A = ReLU(Z)

print(A)

tensor([[1.4628, 1.9304, 1.7424, 0.0000, 2.0341],
        [1.8148, 2.8405, 0.7133, 3.1585, 0.0000],
        [0.0000, 0.8103, 0.0000, 0.3271, 2.3345],
        [0.0000, 1.9673, 2.2396, 5.1747, 0.3568],
        [0.0000, 1.2024, 1.4051, 0.0000, 3.4587],
        [0.0000, 0.0000, 0.0000, 0.0000, 2.7331],
        [0.0000, 1.2425, 0.6161, 0.9942, 2.1074],
        [0.0000, 1.2177, 0.6086, 1.7837, 2.3200],
        [2.6548, 0.0000, 0.0000, 0.0000, 0.0000],
        [4.7414, 0.0000, 0.9934, 0.0000, 1.2204]])


# Problem 3: 

- $x^{(3)}$ 를 입력으로하는 2번째 Neuron의 결과값을 출력하세요
- 위에서 구한 `A[i, j]`  인덱싱을 통해서 출력하세요
- `Python`의 인덱싱은 `0`부터 시작한다는 것을 주의하세요

In [ ]:
# 답 작성

print('answer = ', A[2, 1])

answer =  tensor(1.1958)


# Problem 4: Multi-Layer network

- 3개의 layer가 있는 network를 구성합니다.
- 2번째 layer의 입력 크기는 $k^{[1]}=16$, 출력 크기는 $k^{[2]}=6$
- 마지막 layer의 출력은 $k^{[3]}=1$개의 neuron으로 구성
- 각 layer의 연산값을 구하세요. 
  - 각 layer의 선형 변환 결과값은 `Z1`, `Z2`, `Z3`로 저장하세요
  - 각 layer의 결과값은 `A1`, `A2`, `A3`로 저장하세요
- 모든 weight는 Gaussian 랜덤 변수로 생성, bias는 1로 구성된 벡터로 생성함
- 각 layer의 weight는 `W1`, `W2`, `W3`로하고, bias는 `b1`, `b2`, `b3`로 생성함
- Activation 함수는 `ReLU`를 적용하세요
- Loop 없이 행렬연산으로 구생하세요

In [ ]:
# 답 작성
#X_batch(4 x 10)
W1= torch.randn(4,16)
W2= torch.randn(16,6)
W3= torch.randn(6,1)
b1= torch.randn(10,16)
b2= torch.randn(10,6)
b3= torch.randn(10,1)

Z1 = torch.add(torch.matmul(X_batch,W1),b1)
A1 = ReLU(Z1)
Z2 = torch.add(torch.matmul(A1,W2),b2)
A2 = ReLU(Z2)
Z3 = torch.add(torch.matmul(A2,W3),b3) 
A3= ReLU(Z3)





In [ ]:
print(Z1.shape)
print(Z1)


torch.Size([10, 16])
tensor([[ 1.3965,  3.3318, -2.7778,  0.6777,  0.8293, -2.2252,  0.9632,  0.5943,
          0.1613,  2.0459,  1.8352,  0.3523,  0.6498, -2.1673, -1.7040, -1.4087],
        [-0.2542, -2.0121, -4.5212,  2.5301, -0.0613,  2.7345,  0.8815, -3.0281,
          2.5351, -3.2095, -0.5035,  3.3415, -2.7684, -5.1268,  2.2618, -2.0164],
        [-0.6609,  4.4134,  1.8273,  1.9412, -0.1793, -1.7065, -0.5464,  1.0321,
         -0.4691,  4.0308,  2.3676, -0.2298,  2.2407,  2.4497, -2.9524, -2.0576],
        [-1.1050, -2.3983,  1.2923, -0.4841, -1.3498,  2.1929, -1.7050,  0.6444,
          1.0799, -2.0810, -0.8460,  1.0903, -2.5134, -3.6423,  2.0043,  0.1092],
        [ 2.1356,  3.4715,  2.6039,  0.8777, -0.8044, -4.6825, -0.7029,  5.1988,
         -3.0278,  4.4924,  2.4911, -2.3280,  2.1252,  2.1511, -2.7072,  1.3035],
        [-0.0921,  2.4784,  2.6864,  0.9587, -0.9666, -1.2776, -2.3343,  1.8303,
         -2.5769,  6.2104,  1.5944, -1.9319,  4.0570, 10.1131, -2.6189,  3.6802],
 

In [ ]:
print(Z2.shape)
print(Z2)


torch.Size([10, 6])
tensor([[ 2.5190e+00,  1.3521e+01,  6.9098e+00,  3.7462e-01,  2.3835e+00,
         -5.8937e+00],
        [ 1.4348e+00, -7.2728e+00, -2.2811e+00, -4.8635e+00,  3.2190e-01,
          9.2533e+00],
        [ 6.1557e+00,  2.4807e+01,  9.8516e+00,  1.2058e+00, -5.3691e+00,
         -7.2355e+00],
        [-1.5967e-01, -5.2809e+00,  2.8553e+00, -1.9418e+00,  1.9732e+00,
          7.8655e+00],
        [ 6.9917e+00,  2.5972e+01,  9.5147e+00,  1.7095e-01, -7.0582e-01,
         -2.8162e+00],
        [ 1.4599e+01,  2.7318e+01,  8.5156e+00,  5.9336e+00, -1.5492e+01,
         -1.8271e+01],
        [ 2.2121e+00,  1.2457e+01,  5.4034e+00, -1.5416e+00, -2.2739e+00,
          1.2736e+00],
        [-7.3316e-01,  1.8628e+01,  4.0927e+00, -8.5138e-01,  2.8913e+00,
          2.0664e+00],
        [ 3.7081e+00, -3.1217e+00,  1.8452e+00, -7.3169e-01, -7.3654e-03,
         -2.5304e+00],
        [ 4.9717e+00,  9.0720e+00, -2.1711e+00,  4.9885e+00, -5.3305e+00,
         -9.1542e+00]])


In [ ]:
print(Z3.shape)
print(Z3)

torch.Size([10, 1])
tensor([[ -0.3643],
        [-11.4960],
        [  3.5035],
        [-14.9579],
        [  0.1458],
        [ 12.0582],
        [ -4.1134],
        [  6.0082],
        [ -6.0862],
        [ 16.5274]])


# Problem 5
- 위에서 구한 `A3[i,j]`의 인덱싱을 통해서 $h_\theta(x^{(3)})$ 을 출력하세요
- 역시 `python`인덱싱은 `0` 부터 시작한다는 것을 주의하세요

In [ ]:
# 답 작성

# print('h_theta(x3) = ', A3[?,?])

# Problem 6
위에서 공부한 것을 함수로 만들어 보도록 하겠습니다.
아래 한 layer의 선형 변환을 연산하는 class를 만들어 보도록 하죠.

- Class는 `my_linear_layer()`
  - `__init__(self, n_input, n_output)` 함수:
    - `self.W` 변수 초기화: Weight 행렬 `self.W`를 램덤 Gaussian 생성 (차원에 맞는...)
    - `self.b` 변수 초기화: bias 벡터 `self.b`를 모두 `1`인 벡터 생성 (차원에 맞는...)
  - `forward(A)` 함수:
    - 입력: `A`는 sample batch $X$ 또는 전 layer에서 들어오는 입력 batch $A^{[\ell-1]}$을 입력하는 자리
    - return 값
      - `Z` 변수는 $A^{[\ell-1]}$의 선형 변환 값, 즉 $Z^{[\ell]}$



In [ ]:
# 답 작성
class my_linear_layer():
    def __init__(self, n_input, n_output):
        #self.W = 
        #self.b = 
    
    def forward(self,A):
        #Z = 
        return Z
    
    
    

답을 확인하기 위해서 `n_input=num_feature`과 `n_output = 5` 인 `my_linear_layer` instance 생성

In [ ]:
mll = my_linear_layer(num_feature, 5)
mll.forward(X_batch)

In [ ]:
print(mll.W)
print(mll.b)

# Building a Linear Layer with `torch.nn`
위에서 수행한 작업을 `pytorch`에서는 `torch.nn.Linear`라는 명령어로 쉽게 구현할 수 있습니다.
아래 예제를 보도록 하죠

In [ ]:
import torch.nn as nn
#W = torch.randn(num_feature, 5)
L1 = nn.Linear(num_feature, 5)
Zll = L1(X_batch)
Zll

In [ ]:
L1.weight = nn.Parameter(W.T)
L1.bias.data.fill_(1.0)
Zll2 = L1(X_batch)
Zll2

In [ ]:
Z